/**
 * iSchool — Lightbase Collection Schema Setup
 *
 * Recreates all collections with flexible schemas that work with
 * Lightbase's auto-generated string IDs. The original collections
 * enforced `school_id` as integer, but Lightbase generates string IDs
 * like "g7jr4nbx9rnmzs20cfk1kawxvr" for documents, so we use string
 * type for all foreign key references.
 *
 * Usage:
 *   node --experimental-strip-types scripts/setup-lightbase-collections.ts
 */

const API_KEY = process.env.LIGHTBASE_API_KEY || '';
const PROJECT = process.env.LIGHTBASE_PROJECT || 'ischool-beta';
const BASE_URL = process.env.LIGHTBASE_BASE_URL || '';

if (!API_KEY || !BASE_URL) {
  console.error('ERROR: LIGHTBASE_API_KEY and LIGHTBASE_BASE_URL environment variables are required.');
  process.exit(1);
}

const HEADERS: Record<string, string> = {
  'apikey': API_KEY,
  'x-lightbase-project': PROJECT,
  'Content-Type': 'application/json',
};
const COLL_URL = `${BASE_URL}/api/v1/projects/${PROJECT}/collections`;

async function listCollections(): Promise<Set<string>> {
  const res = await fetch(COLL_URL, { headers: HEADERS });
  if (!res.ok) throw new Error(`listCollections failed: ${res.status}`);
  const data = await res.json();
  const arr = data.collections || [];
  return new Set(arr.map((c: any) => c.name));
}

async function deleteCollection(name: string): Promise<void> {
  const res = await fetch(`${COLL_URL}/${name}`, {
    method: 'DELETE',
    headers: HEADERS,
  });
  if (res.ok) console.log(`  [deleted] ${name}`);
  else console.log(`  [skip-delete] ${name} (${res.status})`);
}

async function createCollection(name: string, fields: any[]): Promise<void> {
  const res = await fetch(COLL_URL, {
    method: 'POST',
    headers: HEADERS,
    body: JSON.stringify({ name, fields }),
  });
  if (res.ok) {
    console.log(`  [created] ${name}`);
    return;
  }
  const err = await res.json().catch(() => ({}));
  const msg = err.error?.message || '';
  if (msg.includes('already exists')) {
    console.log(`  [exists]  ${name}`);
    return;
  }
  console.warn(`  [fail]    ${name}: ${res.status} ${msg.substring(0, 100)}`);
}

// Field type shortcuts — Lightbase requires unique fields to be indexed
const f = {
  str: (name: string, required = false, unique = false, def?: string) => ({
    name, type: 'string', required, unique, indexed: unique || false,
    ...(def !== undefined ? { default: def } : {}),
  }),
  text: (name: string, required = false) => ({ name, type: 'text', required }),
  int: (name: string, required = false, def?: number) => ({ name, type: 'integer', required, ...(def !== undefined ? { default: def } : {}) }),
  bool: (name: string, required = false, def = false) => ({ name, type: 'boolean', required, default: def }),
  json: (name: string, required = false, def = '{}') => ({ name, type: 'json', required, default: def }),
  float: (name: string, required = false) => ({ name, type: 'number', required }),
};

// Common schema patterns
const timestamps = [
  f.str('created_at', false),
  f.str('updated_at', false),
];

// ═══════════════════════════════════════════════════════════
// COLLECTION SCHEMAS — all use string for IDs (Lightbase auto-gen)
// ═══════════════════════════════════════════════════════════

const SCHEMAS: Record<string, any[]> = {
  // Core
  users: [
    f.str('email', true, true),
    f.str('password_hash', true),
    f.str('name', true),
    f.str('role', true, false, 'school_admin'),
    f.str('avatar_url'),
    f.bool('two_factor_enabled', false, false),
    f.str('two_factor_secret'),
    f.str('preferred_language', false, false, 'en'),
    f.bool('is_active', false, true),
    ...timestamps,
  ],
  sessions: [
    f.str('session_id', true, true),
    f.str('user_id', true),
    f.str('expires_at', true),
    f.str('created_at'),
  ],
  password_reset_tokens: [
    f.str('user_id', true),
    f.str('token', true, true),
    f.str('expires_at', true),
    f.bool('used', false, false),
    f.str('created_at'),
  ],
  schools: [
    f.str('name', true),
    f.str('slug', true, true),
    f.str('tagline'),
    f.text('description'),
    f.str('primary_color', false, false, '#05B34D'),
    f.str('secondary_color', false, false, '#F2B91C'),
    f.str('logo_url'),
    f.str('favicon_url'),
    f.str('address'),
    f.str('phone'),
    f.str('email'),
    f.str('website'),
    f.str('domain'),
    f.str('theme', false, false, 'aurora'),
    f.str('locale', false, false, 'en'),
    f.json('module_settings'),
    f.json('settings'),
    f.json('social_handles'),
    f.json('active_modules', false, '["cms","sis","lms","finance","communication"]'),
    f.str('owner_id'),
    f.str('status', false, false, 'active'),
    f.bool('is_active', false, true),
    ...timestamps,
  ],
  school_members: [
    f.str('school_id', true),
    f.str('user_id', true),
    f.str('role', true, false, 'editor'),
    f.bool('active', false, true),
    f.str('created_at'),
  ],
  about_pages: [
    f.str('school_id', true),
    f.text('content'),
    f.text('mission'),
    f.text('vision'),
    f.text('history'),
    f.json('features', false, '[]'),
    f.json('stats', false, '[]'),
    f.json('values', false, '[]'),
    f.text('value_proposition'),
    ...timestamps,
  ],
  announcements: [
    f.str('school_id', true),
    f.str('title', true),
    f.str('slug', true),
    f.text('content', true),
    f.text('excerpt'),
    f.str('banner_image_url'),
    f.str('cta_text'),
    f.str('cta_url'),
    f.bool('is_pinned', false, false),
    f.bool('published', false, true),
    ...timestamps,
  ],
  classes: [
    f.str('school_id', true),
    f.str('name', true),
    f.str('slug'),
    f.str('section'),
    f.text('description'),
    f.text('content'),
    f.str('grade_level'),
    f.str('teacher_name'),
    f.int('capacity'),
    f.str('image_url'),
    f.bool('has_detail_page', false, true),
    f.str('homeroom_teacher_id'),
    f.int('sort_order', false, 0),
    ...timestamps,
  ],
  blog_posts: [
    f.str('school_id', true),
    f.str('title', true),
    f.str('slug', true),
    f.text('content', true),
    f.text('excerpt'),
    f.str('cover_image_url'),
    f.str('author'),
    f.str('category'),
    f.json('tags', false, '[]'),
    f.str('status', false, false, 'published'),
    f.bool('is_published', false, true),
    f.str('published_at'),
    ...timestamps,
  ],
  programs: [
    f.str('school_id', true),
    f.str('name', true),
    f.str('slug'),
    f.text('description'),
    f.text('content'),
    f.bool('is_published', false, true),
    f.int('sort_order', false, 0),
    ...timestamps,
  ],
  faqs: [
    f.str('school_id', true),
    f.str('question', true),
    f.text('answer', true),
    f.str('category'),
    f.int('sort_order', false, 0),
    f.bool('is_published', false, true),
    ...timestamps,
  ],
  gallery_items: [
    f.str('school_id', true),
    f.str('title', true),
    f.text('description'),
    f.str('image_url'),
    f.str('album_id'),
    f.int('sort_order', false, 0),
    f.bool('is_published', false, true),
    ...timestamps,
  ],
  gallery_albums: [
    f.str('school_id', true),
    f.str('name', true),
    f.text('description'),
    f.str('cover_image_url'),
    f.int('sort_order', false, 0),
    f.bool('is_published', false, true),
    ...timestamps,
  ],
  contact_info: [
    f.str('school_id', true),
    f.str('type', false, false, 'general'),
    f.str('label', true),
    f.str('value', true),
    f.int('sort_order', false, 0),
    ...timestamps,
  ],
  contact_submissions: [
    f.str('school_id', true),
    f.str('form_type', false, false, 'general'),
    f.json('data', true),
    f.str('status', false, false, 'new'),
    ...timestamps,
  ],
  navigation_items: [
    f.str('school_id', true),
    f.str('label', true),
    f.str('url', true),
    f.str('parent_id'),
    f.int('sort_order', false, 0),
    f.bool('is_external', false, false),
    ...timestamps,
  ],
  platform_blog_posts: [
    f.str('title', true),
    f.str('slug', true, true),
    f.text('content', true),
    f.text('excerpt'),
    f.str('cover_image_url'),
    f.str('author_id'),
    f.str('category', false, false, 'News'),
    f.json('tags', false, '[]'),
    f.bool('is_published', false, false),
    f.str('published_at'),
    ...timestamps,
  ],
  platform_docs: [
    f.str('title', true),
    f.str('slug', true, true),
    f.text('content', true),
    f.text('excerpt'),
    f.str('category'),
    f.int('sort_order', false, 0),
    f.bool('is_published', false, true),
    ...timestamps,
  ],
  email_logs: [
    f.str('school_id'),
    f.str('to_email', true),
    f.str('subject'),
    f.text('body'),
    f.str('status'),
    f.str('error'),
    ...timestamps,
  ],
  reactions: [
    f.str('school_id'),
    f.str('user_id'),
    f.str('target_type'),
    f.str('target_id'),
    f.str('type'),
    ...timestamps,
  ],
  students: [
    f.str('school_id', true),
    f.str('user_id'),
    f.str('student_id', true, true),
    f.str('first_name', true),
    f.str('last_name', true),
    f.str('gender'),
    f.str('email'),
    f.str('phone'),
    f.str('address'),
    f.str('date_of_birth'),
    f.str('parent_name'),
    f.str('parent_phone'),
    f.str('enrollment_date'),
    f.str('status', false, false, 'active'),
    f.json('custom_fields', false, '{}'),
    f.json('documents', false, '[]'),
    ...timestamps,
  ],
  student_documents: [
    f.str('school_id', true),
    f.str('student_id', true),
    f.str('name'),
    f.str('file_url'),
    f.str('type'),
    ...timestamps,
  ],
  student_medical_records: [
    f.str('school_id', true),
    f.str('student_id', true),
    f.text('conditions'),
    f.text('allergies'),
    f.text('medications'),
    f.str('blood_type'),
    f.str('emergency_contact'),
    ...timestamps,
  ],
  student_emergency_contacts: [
    f.str('school_id', true),
    f.str('student_id', true),
    f.str('name', true),
    f.str('relationship'),
    f.str('phone'),
    f.str('email'),
    ...timestamps,
  ],
  family_groups: [
    f.str('school_id', true),
    f.str('name', true),
    f.json('student_ids', false, '[]'),
    f.json('parent_ids', false, '[]'),
    ...timestamps,
  ],
  enrollments: [
    f.str('school_id', true),
    f.str('student_id', true),
    f.str('class_id', true),
    f.str('academic_year'),
    f.str('status', false, false, 'accepted'),
    ...timestamps,
  ],
  attendance: [
    f.str('school_id', true),
    f.str('student_id', true),
    f.str('class_id'),
    f.str('date', true),
    f.str('status', true),
    f.str('notes'),
    ...timestamps,
  ],
  courses: [
    f.str('school_id', true),
    f.str('title', true),
    f.str('slug'),
    f.text('description'),
    f.str('subject'),
    f.str('grade_level'),
    f.str('teacher_id'),
    f.str('status', false, false, 'published'),
    f.json('settings', false, '{}'),
    ...timestamps,
  ],
  course_units: [
    f.str('school_id', true),
    f.str('course_id', true),
    f.str('title', true),
    f.str('slug'),
    f.text('description'),
    f.int('sort_order', false, 0),
    ...timestamps,
  ],
  lessons: [
    f.str('school_id', true),
    f.str('course_id', true),
    f.str('title', true),
    f.str('slug'),
    f.text('content'),
    f.str('video_url'),
    f.int('sort_order', false, 0),
    f.str('status', false, false, 'published'),
    f.int('duration_minutes'),
    ...timestamps,
  ],
  assignments: [
    f.str('school_id', true),
    f.str('course_id'),
    f.str('lesson_id'),
    f.str('title', true),
    f.text('description'),
    f.str('due_date'),
    f.int('total_marks'),
    f.str('status'),
    ...timestamps,
  ],
  submissions: [
    f.str('school_id', true),
    f.str('assignment_id', true),
    f.str('student_id', true),
    f.text('content'),
    f.str('file_url'),
    f.int('score'),
    f.str('feedback'),
    f.str('status', false, false, 'submitted'),
    f.str('submitted_at'),
    ...timestamps,
  ],
  quizzes: [
    f.str('school_id', true),
    f.str('course_id'),
    f.str('title', true),
    f.text('description'),
    f.int('time_limit_minutes'),
    f.str('status'),
    ...timestamps,
  ],
  questions: [
    f.str('school_id', true),
    f.str('quiz_id', true),
    f.text('question', true),
    f.json('options', false, '[]'),
    f.str('correct_answer'),
    f.int('marks'),
    f.str('type'),
    ...timestamps,
  ],
  quiz_attempts: [
    f.str('school_id', true),
    f.str('quiz_id', true),
    f.str('student_id', true),
    f.int('score'),
    f.json('answers', false, '[]'),
    f.str('status'),
    ...timestamps,
  ],
  grades: [
    f.str('school_id', true),
    f.str('student_id', true),
    f.str('course_id'),
    f.str('assignment_id'),
    f.str('exam_id'),
    f.float('score'),
    f.str('grade'),
    f.str('term'),
    ...timestamps,
  ],
  academic_periods: [
    f.str('school_id', true),
    f.str('name', true),
    f.str('type'),
    f.str('start_date'),
    f.str('end_date'),
    f.str('status'),
    f.bool('is_active', false, false),
    ...timestamps,
  ],
  prayer_schedules: [
    f.str('school_id', true),
    f.str('name', true),
    f.str('applies_to'),
    f.json('periods', false, '[]'),
    f.str('fajr_time'),
    f.str('dhuhr_time'),
    f.str('asr_time'),
    f.str('maghrib_time'),
    f.str('isha_time'),
    f.bool('play_adhan', false, false),
    f.text('notes'),
    ...timestamps,
  ],
  timetable_entries: [
    f.str('school_id', true),
    f.str('class_id'),
    f.str('subject'),
    f.str('teacher_id'),
    f.str('day'),
    f.str('start_time'),
    f.str('end_time'),
    f.str('room'),
    ...timestamps,
  ],
  substitute_teachers: [
    f.str('school_id', true),
    f.str('original_teacher_id'),
    f.str('substitute_teacher_id'),
    f.str('class_id'),
    f.str('date'),
    f.str('reason'),
    ...timestamps,
  ],
  exam_series: [
    f.str('school_id', true),
    f.str('name', true),
    f.str('term'),
    f.str('start_date'),
    f.str('end_date'),
    f.str('status'),
    ...timestamps,
  ],
  exams: [
    f.str('school_id', true),
    f.str('series_id'),
    f.str('title', true),
    f.str('subject'),
    f.str('date'),
    f.int('duration_minutes'),
    f.int('total_marks'),
    f.str('status'),
    ...timestamps,
  ],
  exam_results: [
    f.str('school_id', true),
    f.str('exam_id'),
    f.str('student_id'),
    f.float('score'),
    f.str('grade'),
    ...timestamps,
  ],
  report_cards: [
    f.str('school_id', true),
    f.str('student_id'),
    f.str('term'),
    f.str('academic_year'),
    f.json('subjects', false, '[]'),
    f.str('overall_grade'),
    f.text('remarks'),
    ...timestamps,
  ],
  fee_structures: [
    f.str('school_id', true),
    f.str('name', true),
    f.int('amount', true),
    f.str('frequency'),
    f.str('grade_level'),
    f.text('description'),
    f.bool('is_active', false, true),
    ...timestamps,
  ],
  invoices: [
    f.str('school_id', true),
    f.str('student_id'),
    f.str('invoice_number', true, true),
    f.int('amount', true),
    f.int('paid_amount', false, 0),
    f.str('status', false, false, 'unpaid'),
    f.str('issue_date'),
    f.str('due_date'),
    f.text('description'),
    ...timestamps,
  ],
  payments: [
    f.str('school_id', true),
    f.str('student_id'),
    f.str('invoice_id'),
    f.int('amount', true),
    f.str('method'),
    f.str('reference'),
    f.str('status'),
    f.str('payment_date'),
    f.text('notes'),
    ...timestamps,
  ],
  staff: [
    f.str('school_id', true),
    f.str('user_id'),
    f.str('staff_id', true, true),
    f.str('first_name', true),
    f.str('last_name', true),
    f.str('photo_url'),
    f.str('department'),
    f.str('designation'),
    f.str('employment_type', false, false, 'full_time'),
    f.str('email'),
    f.str('phone'),
    f.text('address'),
    f.json('qualifications', false, '[]'),
    f.json('certifications', false, '[]'),
    f.str('join_date'),
    f.int('salary'),
    f.str('gender'),
    f.str('status', false, false, 'active'),
    ...timestamps,
  ],
  leave_requests: [
    f.str('school_id', true),
    f.str('staff_id'),
    f.str('type'),
    f.str('start_date'),
    f.str('end_date'),
    f.text('reason'),
    f.str('status'),
    ...timestamps,
  ],
  staff_attendance: [
    f.str('school_id', true),
    f.str('staff_id'),
    f.str('date'),
    f.str('status'),
    f.str('check_in'),
    f.str('check_out'),
    ...timestamps,
  ],
  leave_balances: [
    f.str('school_id', true),
    f.str('staff_id'),
    f.str('leave_type'),
    f.int('total_days'),
    f.int('used_days'),
    ...timestamps,
  ],
  job_postings: [
    f.str('school_id', true),
    f.str('title', true),
    f.text('description'),
    f.str('department'),
    f.str('type'),
    f.str('status'),
    ...timestamps,
  ],
  job_applications: [
    f.str('school_id', true),
    f.str('job_id'),
    f.str('name'),
    f.str('email'),
    f.str('phone'),
    f.text('cover_letter'),
    f.str('resume_url'),
    f.str('status'),
    ...timestamps,
  ],
  interviews: [
    f.str('school_id', true),
    f.str('application_id'),
    f.str('date'),
    f.str('time'),
    f.str('location'),
    f.str('status'),
    ...timestamps,
  ],
  performance_appraisals: [
    f.str('school_id', true),
    f.str('staff_id'),
    f.str('period'),
    f.int('rating'),
    f.text('strengths'),
    f.text('areas_for_improvement'),
    f.text('goals'),
    ...timestamps,
  ],
  payroll: [
    f.str('school_id', true),
    f.str('staff_id'),
    f.str('month'),
    f.int('basic_salary'),
    f.int('allowances'),
    f.int('deductions'),
    f.int('net_pay'),
    f.str('status'),
    ...timestamps,
  ],
  messages: [
    f.str('school_id', true),
    f.str('sender_id'),
    f.str('receiver_id'),
    f.text('subject'),
    f.text('body'),
    f.bool('read', false, false),
    f.str('parent_id'),
    ...timestamps,
  ],
  notifications: [
    f.str('school_id'),
    f.str('user_id'),
    f.str('title'),
    f.text('message'),
    f.str('type'),
    f.str('link'),
    f.bool('read', false, false),
    ...timestamps,
  ],
  library_books: [
    f.str('school_id', true),
    f.str('title', true),
    f.str('author'),
    f.str('isbn'),
    f.str('category'),
    f.int('copies_total'),
    f.int('copies_available'),
    f.str('status'),
    f.str('shelf_location'),
    ...timestamps,
  ],
  library_loans: [
    f.str('school_id', true),
    f.str('book_id'),
    f.str('student_id'),
    f.str('issue_date'),
    f.str('due_date'),
    f.str('return_date'),
    f.int('fine'),
    f.str('status'),
    ...timestamps,
  ],
  library_reservations: [
    f.str('school_id', true),
    f.str('book_id'),
    f.str('student_id'),
    f.str('reserved_at'),
    f.str('status'),
    ...timestamps,
  ],
  hostels: [
    f.str('school_id', true),
    f.str('name', true),
    f.int('capacity'),
    f.int('occupied', false, 0),
    f.str('warden_name'),
    f.str('warden_phone'),
    f.str('status'),
    ...timestamps,
  ],
  hostel_rooms: [
    f.str('school_id', true),
    f.str('hostel_id'),
    f.str('room_number'),
    f.int('capacity'),
    f.int('occupied', false, 0),
    f.str('status'),
    ...timestamps,
  ],
  hostel_allocations: [
    f.str('school_id', true),
    f.str('student_id'),
    f.str('room_id'),
    f.str('allocated_at'),
    f.str('vacated_at'),
    f.str('status'),
    ...timestamps,
  ],
  hostel_checkins: [
    f.str('school_id', true),
    f.str('student_id'),
    f.str('check_in_at'),
    f.str('check_out_at'),
    ...timestamps,
  ],
  hostel_visitors: [
    f.str('school_id', true),
    f.str('student_id'),
    f.str('visitor_name'),
    f.str('relationship'),
    f.str('visit_date'),
    f.str('check_in'),
    f.str('check_out'),
    ...timestamps,
  ],
  hostel_maintenance_requests: [
    f.str('school_id', true),
    f.str('room_id'),
    f.str('reported_by'),
    f.text('issue'),
    f.str('priority'),
    f.str('status'),
    ...timestamps,
  ],
  vehicles: [
    f.str('school_id', true),
    f.str('registration', true, true),
    f.str('type'),
    f.int('capacity'),
    f.str('model'),
    f.int('year'),
    f.str('status'),
    ...timestamps,
  ],
  transport_routes: [
    f.str('school_id', true),
    f.str('name', true),
    f.text('description'),
    f.json('stops', false, '[]'),
    f.int('fare', false, 0),
    f.str('status'),
    ...timestamps,
  ],
  transport_assignments: [
    f.str('school_id', true),
    f.str('student_id'),
    f.str('route_id'),
    f.str('vehicle_id'),
    f.str('status'),
    ...timestamps,
  ],
  transport_dispatch: [
    f.str('school_id', true),
    f.str('vehicle_id'),
    f.str('route_id'),
    f.str('dispatch_date'),
    f.str('driver_name'),
    f.str('status'),
    ...timestamps,
  ],
  transport_boarding: [
    f.str('school_id', true),
    f.str('student_id'),
    f.str('route_id'),
    f.str('boarded_at'),
    f.str('alighted_at'),
    ...timestamps,
  ],
  vehicle_maintenance: [
    f.str('school_id', true),
    f.str('vehicle_id'),
    f.str('date'),
    f.text('description'),
    f.int('cost'),
    f.str('status'),
    ...timestamps,
  ],
  vehicle_documents: [
    f.str('school_id', true),
    f.str('vehicle_id'),
    f.str('name'),
    f.str('file_url'),
    f.str('expiry_date'),
    ...timestamps,
  ],
  assets: [
    f.str('school_id', true),
    f.str('name', true),
    f.str('asset_tag', true, true),
    f.str('category'),
    f.str('condition'),
    f.str('location'),
    f.int('value'),
    f.str('status'),
    ...timestamps,
  ],
  asset_checkouts: [
    f.str('school_id', true),
    f.str('asset_id'),
    f.str('staff_id'),
    f.str('checkout_date'),
    f.str('return_date'),
    f.str('status'),
    ...timestamps,
  ],
  suppliers: [
    f.str('school_id', true),
    f.str('name', true),
    f.str('contact_person'),
    f.str('phone'),
    f.str('email'),
    f.text('address'),
    ...timestamps,
  ],
  purchase_requests: [
    f.str('school_id', true),
    f.str('item_name'),
    f.int('quantity'),
    f.int('estimated_cost'),
    f.str('requested_by'),
    f.str('status'),
    ...timestamps,
  ],
  inventory_items: [
    f.str('school_id', true),
    f.str('name', true),
    f.str('category'),
    f.int('quantity'),
    f.int('reorder_level'),
    f.str('unit'),
    f.str('location'),
    ...timestamps,
  ],
  events: [
    f.str('school_id', true),
    f.str('title', true),
    f.text('description'),
    f.str('start_date'),
    f.str('end_date'),
    f.str('location'),
    f.str('status'),
    ...timestamps,
  ],
  event_rsvps: [
    f.str('school_id', true),
    f.str('event_id'),
    f.str('user_id'),
    f.str('status'),
    ...timestamps,
  ],
  venues: [
    f.str('school_id'),
    f.str('name', true),
    f.int('capacity'),
    f.str('location'),
    f.bool('is_active', false, true),
    ...timestamps,
  ],
  behavior_logs: [
    f.str('school_id', true),
    f.str('student_id'),
    f.str('logged_by'),
    f.str('type'),
    f.text('description'),
    f.str('date'),
    ...timestamps,
  ],
  lesson_plans: [
    f.str('school_id', true),
    f.str('lesson_id'),
    f.str('teacher_id'),
    f.text('objectives'),
    f.text('activities'),
    f.text('assessment'),
    ...timestamps,
  ],
  seating_plans: [
    f.str('school_id', true),
    f.str('class_id'),
    f.json('layout', false, '{}'),
    ...timestamps,
  ],
  interactive_lessons: [
    f.str('school_id', true),
    f.str('lesson_id'),
    f.str('type'),
    f.json('content', false, '{}'),
    ...timestamps,
  ],
  saved_reports: [
    f.str('school_id'),
    f.str('user_id'),
    f.str('name'),
    f.str('type'),
    f.json('config', false, '{}'),
    ...timestamps,
  ],
  audit_logs: [
    f.str('school_id'),
    f.str('user_id'),
    f.str('action'),
    f.json('details', false, '{}'),
    f.str('ip_address'),
    ...timestamps,
  ],
  module_settings: [
    f.str('school_id', true),
    f.str('module', true),
    f.bool('enabled', false, true),
    f.json('config', false, '{}'),
    ...timestamps,
  ],
  role_overrides: [
    f.str('school_id', true),
    f.str('role', true),
    f.str('permission', true),
    f.str('action'),
    ...timestamps,
  ],
  fee_access_rules: [
    f.str('school_id', true),
    f.str('module'),
    f.int('grace_period_days'),
    f.bool('block_exams', false, false),
    ...timestamps,
  ],
  discussion_boards: [
    f.str('school_id', true),
    f.str('course_id'),
    f.str('title', true),
    f.text('description'),
    ...timestamps,
  ],
  discussion_posts: [
    f.str('school_id', true),
    f.str('board_id'),
    f.str('author_id'),
    f.text('content'),
    f.str('parent_id'),
    ...timestamps,
  ],
  cbt_exams: [
    f.str('school_id', true),
    f.str('title', true),
    f.str('subject'),
    f.int('duration_minutes'),
    f.int('total_marks'),
    f.str('start_time'),
    f.str('end_time'),
    f.str('status'),
    ...timestamps,
  ],
  cbt_candidates: [
    f.str('school_id', true),
    f.str('exam_id'),
    f.str('student_id'),
    f.str('status'),
    ...timestamps,
  ],
  cbt_attempts: [
    f.str('school_id', true),
    f.str('exam_id'),
    f.str('student_id'),
    f.int('score'),
    f.str('started_at'),
    f.str('submitted_at'),
    f.str('status'),
    ...timestamps,
  ],
  cbt_proctoring_logs: [
    f.str('school_id', true),
    f.str('attempt_id'),
    f.str('event_type'),
    f.text('description'),
    f.str('timestamp'),
    ...timestamps,
  ],
  cbt_sections: [
    f.str('school_id', true),
    f.str('exam_id'),
    f.str('name'),
    f.str('description'),
    f.int('sort_order'),
    ...timestamps,
  ],
  cbt_question_tags: [
    f.str('school_id', true),
    f.str('tag', true),
    ...timestamps,
  ],
  notification_templates: [
    f.str('name', true),
    f.str('slug', true, true),
    f.str('subject'),
    f.text('body'),
    f.str('type'),
    f.bool('is_active', false, true),
    ...timestamps,
  ],
  banners: [
    f.str('school_id', true),
    f.str('title'),
    f.str('image_url'),
    f.str('link_url'),
    f.str('position'),
    f.str('start_date'),
    f.str('end_date'),
    f.bool('is_active', false, true),
    ...timestamps,
  ],
  popups: [
    f.str('school_id', true),
    f.str('title'),
    f.text('content'),
    f.str('image_url'),
    f.str('button_text'),
    f.str('button_url'),
    f.str('display_rule'),
    f.bool('is_active', false, true),
    ...timestamps,
  ],
  virtual_tours: [
    f.str('school_id', true),
    f.str('title'),
    f.str('panorama_url'),
    f.bool('is_published', false, true),
    f.int('sort_order', false, 0),
    ...timestamps,
  ],
  media_uploads: [
    f.str('school_id'),
    f.str('uploaded_by'),
    f.str('file_url'),
    f.str('file_type'),
    f.int('file_size'),
    ...timestamps,
  ],
  subscription_plans: [
    f.str('name', true),
    f.str('slug', true, true),
    f.text('description'),
    f.int('price_monthly'),
    f.int('price_yearly'),
    f.json('features', false, '[]'),
    f.int('max_students'),
    f.int('max_staff'),
    f.int('max_storage_gb'),
    f.bool('is_active', false, true),
    f.bool('is_popular', false, false),
    f.int('sort_order', false, 0),
    ...timestamps,
  ],
  school_subscriptions: [
    f.str('school_id', true),
    f.str('plan_id'),
    f.str('status'),
    f.str('current_period_start'),
    f.str('current_period_end'),
    f.str('trial_ends_at'),
    ...timestamps,
  ],
  platform_invoices: [
    f.str('school_id'),
    f.str('invoice_number', true, true),
    f.int('amount'),
    f.int('paid_amount', false, 0),
    f.str('status'),
    f.str('issue_date'),
    f.str('due_date'),
    ...timestamps,
  ],
  platform_payments: [
    f.str('school_id'),
    f.str('invoice_id'),
    f.int('amount'),
    f.str('method'),
    f.str('reference'),
    f.str('status'),
    f.str('payment_date'),
    ...timestamps,
  ],
  coupons: [
    f.str('code', true, true),
    f.str('type'),
    f.int('value'),
    f.str('valid_from'),
    f.str('valid_until'),
    f.int('max_uses'),
    f.int('used_count', false, 0),
    f.bool('is_active', false, true),
    ...timestamps,
  ],
  coupon_redemptions: [
    f.str('coupon_id'),
    f.str('school_id'),
    f.str('redeemed_at'),
    ...timestamps,
  ],
  support_tickets: [
    f.str('subject', true),
    f.text('description'),
    f.str('status'),
    f.str('priority'),
    f.str('category'),
    f.str('user_id'),
    f.str('school_id'),
    ...timestamps,
  ],
  support_ticket_replies: [
    f.str('ticket_id'),
    f.str('user_id'),
    f.text('body'),
    ...timestamps,
  ],
  platform_faqs: [
    f.str('question', true),
    f.text('answer', true),
    f.str('category'),
    f.int('sort_order', false, 0),
    f.bool('is_published', false, true),
    ...timestamps,
  ],
  platform_settings: [
    f.str('key', true, true),
    f.text('value'),
    ...timestamps,
  ],
  ai_providers: [
    f.str('name', true),
    f.str('slug', true, true),
    f.str('base_url'),
    f.bool('is_active', false, true),
    f.int('sort_order', false, 0),
    ...timestamps,
  ],
  ai_api_keys: [
    f.str('school_id'),
    f.str('provider_slug'),
    f.text('api_key_encrypted'),
    f.bool('is_active', false, true),
    ...timestamps,
  ],
  ai_models: [
    f.str('provider_slug', true),
    f.str('model_id', true, true),
    f.str('display_name'),
    f.int('context_window'),
    f.bool('is_active', false, true),
    f.int('sort_order', false, 0),
    ...timestamps,
  ],
  ai_conversations: [
    f.str('school_id'),
    f.str('user_id'),
    f.str('title'),
    f.str('model'),
    ...timestamps,
  ],
  ai_messages: [
    f.str('conversation_id'),
    f.str('role'),
    f.text('content'),
    f.json('metadata', false, '{}'),
    ...timestamps,
  ],
  ai_settings: [
    f.str('key', true, true),
    f.text('value'),
    ...timestamps,
  ],
  school_support_tickets: [
    f.str('school_id', true),
    f.str('subject', true),
    f.text('description'),
    f.str('status'),
    f.str('priority'),
    f.str('category'),
    f.str('user_id'),
    ...timestamps,
  ],
  school_ticket_replies: [
    f.str('ticket_id'),
    f.str('user_id'),
    f.text('body'),
    ...timestamps,
  ],
  school_ticket_categories: [
    f.str('name', true),
    f.str('slug', true, true),
    f.text('description'),
    f.int('sort_order', false, 0),
    f.bool('is_active', false, true),
    ...timestamps,
  ],
  subscriber_accounts: [
    f.str('email', true, true),
    f.str('name'),
    f.str('school_id'),
    f.bool('is_active', false, true),
    ...timestamps,
  ],
  live_class_rooms: [
    f.str('school_id', true),
    f.str('title'),
    f.str('teacher_id'),
    f.str('start_time'),
    f.str('end_time'),
    f.str('status'),
    ...timestamps,
  ],
  live_class_messages: [
    f.str('room_id'),
    f.str('user_id'),
    f.text('message'),
    ...timestamps,
  ],
  live_class_polls: [
    f.str('room_id'),
    f.str('question'),
    f.json('options', false, '[]'),
    ...timestamps,
  ],
  live_class_whiteboards: [
    f.str('room_id'),
    f.json('strokes', false, '[]'),
    ...timestamps,
  ],
  webhooks: [
    f.str('school_id'),
    f.str('url'),
    f.str('event'),
    f.bool('is_active', false, true),
    ...timestamps,
  ],
  webhook_deliveries: [
    f.str('webhook_id'),
    f.str('payload'),
    f.str('status'),
    f.str('delivered_at'),
    ...timestamps,
  ],
  data_requests: [
    f.str('type'),
    f.str('user_id'),
    f.str('status'),
    ...timestamps,
  ],
  forms: [
    f.str('school_id', true),
    f.str('title', true),
    f.str('slug'),
    f.text('description'),
    f.json('fields', false, '[]'),
    f.json('settings', false, '{}'),
    f.bool('is_active', false, true),
    ...timestamps,
  ],
  form_submissions: [
    f.str('school_id', true),
    f.str('form_id'),
    f.json('data', false, '{}'),
    f.str('status'),
    ...timestamps,
  ],
  class_subjects: [
    f.str('school_id', true),
    f.str('class_id'),
    f.str('subject'),
    f.str('teacher_id'),
    ...timestamps,
  ],
  admission_periods: [
    f.str('school_id', true),
    f.str('name', true),
    f.str('slug'),
    f.str('open_date'),
    f.str('close_date'),
    f.bool('is_active', false, false),
    f.text('description'),
    f.json('requirements', false, '[]'),
    ...timestamps,
  ],
  admission_applications: [
    f.str('school_id', true),
    f.str('period_id'),
    f.str('student_name'),
    f.str('parent_name'),
    f.str('parent_email'),
    f.str('parent_phone'),
    f.json('data', false, '{}'),
    f.str('status'),
    ...timestamps,
  ],
  gmb_connections: [
    f.str('school_id', true),
    f.str('account_name'),
    f.str('location_id'),
    f.bool('is_active', false, true),
    ...timestamps,
  ],
  gmb_posts: [
    f.str('school_id', true),
    f.str('title'),
    f.text('content'),
    f.str('image_url'),
    f.str('event_date'),
    f.str('status'),
    ...timestamps,
  ],
  gmb_reviews: [
    f.str('school_id', true),
    f.str('reviewer_name'),
    f.int('rating'),
    f.text('comment'),
    f.str('response'),
    f.str('date'),
    ...timestamps,
  ],
  social_accounts: [
    f.str('school_id', true),
    f.str('platform'),
    f.str('handle'),
    f.text('access_token_encrypted'),
    f.bool('is_active', false, true),
    ...timestamps,
  ],
  social_posts: [
    f.str('school_id', true),
    f.str('platform'),
    f.text('content'),
    f.str('image_url'),
    f.str('scheduled_at'),
    f.str('posted_at'),
    f.str('status'),
    ...timestamps,
  ],
  social_analytics: [
    f.str('school_id', true),
    f.str('platform'),
    f.int('likes'),
    f.int('comments'),
    f.int('shares'),
    f.int('impressions'),
    f.str('date'),
    ...timestamps,
  ],
  social_comments: [
    f.str('school_id', true),
    f.str('post_id'),
    f.str('author'),
    f.text('content'),
    f.str('date'),
    ...timestamps,
  ],
  email_lists: [
    f.str('school_id', true),
    f.str('name', true),
    f.text('description'),
    f.int('subscriber_count', false, 0),
    ...timestamps,
  ],
  email_subscribers: [
    f.str('school_id', true),
    f.str('list_id'),
    f.str('email', true),
    f.str('name'),
    f.bool('is_active', false, true),
    ...timestamps,
  ],
  email_campaigns: [
    f.str('school_id', true),
    f.str('title', true),
    f.str('subject'),
    f.text('body'),
    f.str('list_id'),
    f.str('scheduled_at'),
    f.str('sent_at'),
    f.str('status'),
    ...timestamps,
  ],
  email_campaign_stats: [
    f.str('school_id', true),
    f.str('campaign_id'),
    f.int('sent'),
    f.int('opened'),
    f.int('clicked'),
    f.int('bounced'),
    f.int('unsubscribed'),
    ...timestamps,
  ],
  email_automations: [
    f.str('school_id', true),
    f.str('name'),
    f.str('trigger'),
    f.str('action'),
    f.bool('is_active', false, true),
    ...timestamps,
  ],
  email_templates: [
    f.str('name', true),
    f.str('slug', true, true),
    f.str('subject'),
    f.text('body'),
    f.bool('is_active', false, true),
    ...timestamps,
  ],
};

// ═══════════════════════════════════════════════════════════
// MAIN — drop & recreate all collections
// ═══════════════════════════════════════════════════════════

async function main() {
  console.log('═══════════════════════════════════════════════════════');
  console.log('iSchool — Lightbase Collection Setup');
  console.log('Project:', PROJECT);
  console.log('═══════════════════════════════════════════════════════\n');

  const existing = await listCollections();
  console.log(`Found ${existing.size} existing collections.\n`);

  // Delete and recreate each collection in schema order
  const sortedNames = Object.keys(SCHEMAS).sort();
  let created = 0, kept = 0, failed = 0; // kept = existing, preserved untouched

  for (const name of sortedNames) {
    const fields = SCHEMAS[name];
    // Non-destructive ensure variant (ensure-lightbase-collections.ts):
    // SKIP existing collections (they hold live seeded data) — only create missing ones.
    if (existing.has(name)) {
      kept++;
      continue;
    }
    // Create with new schema
    try {
      await createCollection(name, fields);
      created++;
    } catch (e: any) {
      console.warn(`  [error] ${name}: ${e.message.substring(0, 100)}`);
      failed++;
    }
  }

  console.log(`\nDone. Created ${created} collections, ${failed} failed.`);

  // Verify
  const after = await listCollections();
  console.log(`Total collections now: ${after.size}`);
}

main().catch(e => { console.error('FATAL:', e); process.exit(1); });
