/**
 * Lightbase Collection Setup Script
 * 
 * Creates all collections (tables) in Lightbase based on the existing
 * SQLite schema. Run this once when setting up Lightbase.
 * 
 * Usage:
 *   npx tsx scripts/setup-lightbase.ts
 */

import { LightbaseClient } from '../src/lib/lightbase.js';

const client = new LightbaseClient({
  apiKey: process.env.LIGHTBASE_API_KEY || 'lb_live_p8xrxsbw6mrf10yj5n6b3sdt13tapx5xvxzpqvybfnsz8anb0neg',
  project: process.env.LIGHTBASE_PROJECT || 'edulink',
  baseUrl: process.env.LIGHTBASE_BASE_URL || 'http://lightbase.80.225.189.74.sslip.io',
});

// Helper to create a text field
function text(name: string, opts: any = {}) {
  return { name, type: 'text', ...opts };
}
function string(name: string, opts: any = {}) {
  return { name, type: 'string', ...opts };
}
function integer(name: string, opts: any = {}) {
  return { name, type: 'integer', ...opts };
}
function boolean(name: string, opts: any = {}) {
  return { name, type: 'boolean', ...opts };
}
function json(name: string, opts: any = {}) {
  return { name, type: 'json', ...opts };
}

// All collections matching our SQLite tables
const collections: Array<{ name: string; fields: any[] }> = [
  // Core
  { name: 'users', fields: [
    string('email', { required: true, unique: true, indexed: true }),
    string('password_hash', { required: true }),
    string('name', { required: true }),
    string('role', { default: 'school_admin' }),
    string('avatar_url'),
    boolean('is_active', { default: true }),
    string('two_factor_secret'),
    boolean('two_factor_enabled', { default: false }),
    string('phone'),
    string('last_login_at'),
    string('reset_token'),
    string('reset_expires'),
  ]},
  { name: 'sessions', fields: [
    string('session_id', { required: true, unique: true, indexed: true }),
    integer('user_id', { required: true, indexed: true }),
    string('expires_at', { required: true }),
    string('ip_address'),
    string('user_agent'),
  ]},
  { name: 'password_reset_tokens', fields: [
    integer('user_id', { required: true, indexed: true }),
    string('token', { required: true, unique: true }),
    string('expires_at', { required: true }),
  ]},
  { name: 'schools', fields: [
    string('name', { required: true }),
    string('slug', { required: true, unique: true, indexed: true }),
    string('tagline'),
    text('description'),
    string('primary_color'),
    string('secondary_color'),
    string('logo_url'),
    string('favicon_url'),
    string('address'),
    string('phone'),
    string('email'),
    string('website'),
    string('domain'),
    string('theme', { default: 'aurora' }),
    json('module_settings', { default: '{}' }),
    boolean('is_active', { default: true }),
  ]},
  { name: 'school_members', fields: [
    integer('user_id', { required: true, indexed: true }),
    integer('school_id', { required: true, indexed: true }),
    string('role'),
    boolean('active', { default: true }),
  ]},

  // SIS
  { name: 'students', fields: [
    integer('school_id', { required: true, indexed: true }),
    integer('user_id', { indexed: true }),
    string('student_id', { required: true }),
    string('first_name', { required: true }),
    string('last_name', { required: true }),
    string('date_of_birth'),
    string('gender'),
    string('photo_url'),
    string('email'),
    string('phone'),
    text('address'),
    string('emergency_contact_name'),
    string('emergency_contact_phone'),
    text('medical_notes'),
    text('allergies'),
    integer('parent_id', { indexed: true }),
    string('status', { default: 'active', indexed: true }),
    string('enrollment_date'),
    json('custom_fields', { default: '{}' }),
    json('documents', { default: '[]' }),
    integer('family_group_id'),
    string('blood_group'),
    string('nationality'),
    string('religion'),
    string('previous_school'),
  ]},
  { name: 'student_documents', fields: [
    integer('student_id', { required: true, indexed: true }),
    integer('school_id', { required: true }),
    string('category', { required: true }),
    string('title', { required: true }),
    string('file_url', { required: true }),
    string('file_name'),
    string('file_type'),
    integer('uploaded_by'),
  ]},
  { name: 'student_medical_records', fields: [
    integer('student_id', { required: true, indexed: true }),
    integer('school_id', { required: true }),
    string('type', { required: true }),
    string('title', { required: true }),
    text('description'),
    string('severity'),
    string('date'),
    integer('recorded_by'),
  ]},
  { name: 'enrollments', fields: [
    integer('school_id', { required: true, indexed: true }),
    integer('student_id', { required: true, indexed: true }),
    integer('class_id', { indexed: true }),
    string('academic_year', { required: true }),
    string('term'),
    string('status', { default: 'submitted', indexed: true }),
    text('notes'),
  ]},
  { name: 'attendance', fields: [
    integer('school_id', { required: true, indexed: true }),
    integer('student_id', { required: true, indexed: true }),
    string('date', { required: true, indexed: true }),
    string('period'),
    string('status', { required: true }),
    integer('marked_by'),
    text('notes'),
  ]},
  { name: 'classes', fields: [
    integer('school_id', { required: true }),
    string('name', { required: true }),
    string('slug'),
    string('section'),
    text('description'),
    text('content'),
    string('grade_level'),
    string('teacher_name'),
    integer('capacity'),
    string('image_url'),
    boolean('has_detail_page', { default: true }),
    integer('homeroom_teacher_id'),
    integer('sort_order', { default: 0 }),
  ]},

  // LMS
  { name: 'courses', fields: [
    integer('school_id', { required: true }),
    string('title', { required: true }),
    string('slug', { required: true }),
    text('description'),
    string('subject'),
    string('grade_level'),
    integer('teacher_id'),
    string('cover_image_url'),
    string('status', { default: 'draft' }),
    json('settings', { default: '{}' }),
  ]},
  { name: 'course_units', fields: [
    integer('course_id', { required: true }),
    string('title', { required: true }),
    text('description'),
    integer('sort_order', { default: 0 }),
  ]},
  { name: 'lessons', fields: [
    integer('unit_id', { required: true }),
    string('title', { required: true }),
    text('content'),
    string('type', { default: 'text' }),
    string('file_url'),
    string('external_url'),
    integer('duration'),
    integer('sort_order', { default: 0 }),
  ]},
  { name: 'assignments', fields: [
    integer('school_id', { required: true }),
    integer('course_id', { required: true }),
    string('title', { required: true }),
    text('instructions'),
    string('type', { default: 'file_upload' }),
    string('due_date'),
    integer('max_points', { default: 100 }),
    boolean('allow_late', { default: false }),
    boolean('allow_resubmit', { default: false }),
    boolean('is_group', { default: false }),
    json('attachments', { default: '[]' }),
    json('rubric'),
  ]},
  { name: 'submissions', fields: [
    integer('school_id'),
    integer('assignment_id', { required: true }),
    integer('student_id', { required: true }),
    text('content'),
    string('file_url'),
    string('link_url'),
    string('status', { default: 'submitted' }),
    integer('grade'),
    text('feedback'),
    integer('graded_by'),
  ]},
  { name: 'quizzes', fields: [
    integer('school_id', { required: true }),
    integer('course_id'),
    string('title', { required: true }),
    text('description'),
    integer('time_limit'),
    integer('attempts', { default: 1 }),
    integer('passing_score', { default: 50 }),
    boolean('randomize', { default: false }),
    boolean('show_results', { default: true }),
    string('scheduled_start'),
    string('scheduled_end'),
    string('status', { default: 'draft' }),
  ]},
  { name: 'questions', fields: [
    integer('quiz_id'),
    integer('school_id', { required: true }),
    string('type', { required: true }),
    text('question', { required: true }),
    json('options'),
    text('correct_answer'),
    integer('points', { default: 1 }),
    string('difficulty', { default: 'medium' }),
    json('tags', { default: '[]' }),
    text('explanation'),
    integer('sort_order', { default: 0 }),
  ]},
  { name: 'quiz_attempts', fields: [
    integer('school_id'),
    integer('quiz_id', { required: true }),
    integer('student_id', { required: true }),
    json('answers', { required: true }),
    integer('score'),
    integer('max_score'),
    integer('total_points'),
    integer('time_taken'),
    string('status', { default: 'in_progress' }),
  ]},
  { name: 'grades', fields: [
    integer('school_id', { required: true, indexed: true }),
    integer('student_id', { required: true, indexed: true }),
    integer('course_id', { indexed: true }),
    integer('assignment_id', { indexed: true }),
    integer('exam_id'),
    string('term'),
    string('academic_year'),
    string('category'),
    integer('score'),
    integer('max_score'),
    string('grade'),
    text('comment'),
    text('comments'),
  ]},

  // Timetable
  { name: 'academic_periods', fields: [
    integer('school_id', { required: true }),
    string('name', { required: true }),
    string('type', { required: true }),
    string('start_date', { required: true }),
    string('end_date', { required: true }),
    integer('parent_period_id'),
  ]},
  { name: 'prayer_schedules', fields: [
    integer('school_id', { required: true }),
    string('name', { required: true }),
    string('applies_to', { default: 'weekday' }),
    json('periods', { required: true }),
    string('fajr_time'),
    string('dhuhr_time'),
    string('asr_time'),
    string('maghrib_time'),
    string('isha_time'),
    string('jumuah_time'),
    boolean('play_adhan', { default: false }),
    string('adhan_audio_url'),
    text('notes'),
  ]},
  { name: 'timetable_entries', fields: [
    integer('school_id', { required: true }),
    integer('class_id'),
    integer('course_id'),
    integer('teacher_id'),
    integer('day_of_week', { required: true }),
    integer('period_number', { required: true }),
    string('start_time', { required: true }),
    string('end_time', { required: true }),
    string('room'),
  ]},
  { name: 'substitute_teachers', fields: [
    integer('school_id', { required: true }),
    integer('timetable_entry_id'),
    integer('original_teacher_id'),
    integer('substitute_teacher_id'),
    string('date', { required: true }),
    string('reason'),
    text('notes'),
    string('status', { default: 'pending' }),
    integer('approved_by'),
  ]},

  // Exams
  { name: 'exam_series', fields: [
    integer('school_id', { required: true }),
    string('name', { required: true }),
    string('type', { required: true }),
    string('academic_year'),
    string('term'),
    string('start_date'),
    string('end_date'),
    string('status', { default: 'draft' }),
  ]},
  { name: 'exams', fields: [
    integer('school_id', { required: true }),
    integer('series_id', { required: true }),
    string('subject', { required: true }),
    string('title', { required: true }),
    integer('class_id'),
    integer('total_marks', { required: true }),
    integer('passing_marks'),
    integer('duration'),
    string('date'),
    string('venue'),
    string('invigilator'),
    text('instructions'),
  ]},
  { name: 'exam_results', fields: [
    integer('school_id', { required: true }),
    integer('exam_id', { required: true, indexed: true }),
    integer('student_id', { required: true, indexed: true }),
    integer('marks_obtained'),
    string('grade'),
    integer('rank'),
    text('remark'),
    string('status', { default: 'present' }),
  ]},
  { name: 'report_cards', fields: [
    integer('school_id', { required: true }),
    integer('student_id', { required: true }),
    string('academic_year', { required: true }),
    string('term', { required: true }),
    json('results', { required: true }),
    text('class_teacher_comment'),
    text('principal_remark'),
    integer('total_marks'),
    integer('percentage'),
    integer('class_rank'),
    string('promotion_status', { default: 'pending' }),
  ]},

  // Finance
  { name: 'fee_structures', fields: [
    integer('school_id', { required: true }),
    string('name', { required: true }),
    string('grade_level'),
    string('category'),
    json('items', { required: true }),
    integer('total_amount', { required: true }),
    string('frequency', { required: true }),
    string('academic_year'),
  ]},
  { name: 'invoices', fields: [
    integer('school_id', { required: true, indexed: true }),
    integer('student_id', { required: true, indexed: true }),
    string('invoice_number', { required: true }),
    integer('fee_structure_id'),
    integer('amount', { required: true }),
    integer('discount', { default: 0 }),
    integer('fine', { default: 0 }),
    integer('paid_amount', { default: 0 }),
    integer('balance', { required: true }),
    string('status', { default: 'pending', indexed: true }),
    string('due_date'),
  ]},
  { name: 'payments', fields: [
    integer('invoice_id', { required: true, indexed: true }),
    integer('school_id', { required: true, indexed: true }),
    integer('amount', { required: true }),
    string('method', { required: true }),
    string('reference'),
    string('status', { default: 'completed', indexed: true }),
    integer('paid_by'),
    text('notes'),
  ]},

  // HR
  { name: 'staff', fields: [
    integer('school_id', { required: true }),
    integer('user_id'),
    string('staff_id', { required: true }),
    string('first_name', { required: true }),
    string('last_name', { required: true }),
    string('photo_url'),
    string('department'),
    string('designation'),
    string('employment_type', { default: 'full_time' }),
    string('email'),
    string('phone'),
    text('address'),
    json('qualifications', { default: '[]' }),
    json('certifications', { default: '[]' }),
    string('join_date'),
    integer('salary'),
  ]},
  { name: 'leave_requests', fields: [
    integer('school_id', { required: true }),
    integer('staff_id', { required: true }),
    string('leave_type', { required: true }),
    string('start_date', { required: true }),
    string('end_date', { required: true }),
    text('reason'),
    string('status', { default: 'pending' }),
    integer('approved_by'),
  ]},
  { name: 'staff_attendance', fields: [
    integer('school_id', { required: true }),
    integer('staff_id', { required: true }),
    string('date', { required: true }),
    string('clock_in'),
    string('clock_out'),
    string('method', { default: 'manual' }),
    text('notes'),
  ]},
  { name: 'payroll', fields: [
    integer('school_id', { required: true }),
    integer('staff_id', { required: true }),
    string('month', { required: true }),
    integer('year', { required: true }),
    integer('basic_salary', { required: true }),
    json('allowances', { default: '[]' }),
    json('deductions', { default: '[]' }),
    integer('gross_pay', { required: true }),
    integer('net_pay', { required: true }),
    string('status', { default: 'draft' }),
  ]},
  { name: 'job_postings', fields: [
    integer('school_id', { required: true }),
    string('title', { required: true }),
    string('department'),
    text('description'),
    json('requirements', { default: '[]' }),
    string('employment_type', { default: 'full_time' }),
    string('salary_range'),
    string('start_date'),
    string('application_deadline'),
    string('status', { default: 'draft' }),
    integer('created_by'),
  ]},
  { name: 'job_applications', fields: [
    integer('job_id', { required: true }),
    string('applicant_name', { required: true }),
    string('applicant_email', { required: true }),
    string('applicant_phone'),
    text('cover_letter'),
    string('resume_url'),
    string('status', { default: 'submitted' }),
  ]},
  { name: 'interviews', fields: [
    integer('school_id', { required: true }),
    integer('application_id', { required: true }),
    string('scheduled_at', { required: true }),
    integer('duration', { default: 60 }),
    string('location'),
    integer('interviewer_id'),
    text('notes'),
    string('status', { default: 'scheduled' }),
  ]},
  { name: 'performance_appraisals', fields: [
    integer('school_id', { required: true }),
    integer('staff_id', { required: true }),
    string('cycle', { required: true }),
    string('type', { required: true }),
    json('kpis', { default: '[]' }),
    text('strengths'),
    text('improvements'),
    text('goals'),
    integer('overall_rating'),
    integer('reviewer_id'),
    string('status', { default: 'pending' }),
  ]},

  // Communication
  { name: 'messages', fields: [
    integer('school_id', { required: true, indexed: true }),
    integer('sender_id', { required: true, indexed: true }),
    integer('recipient_id', { indexed: true }),
    string('group_id'),
    string('subject'),
    text('content', { required: true }),
    json('attachments', { default: '[]' }),
    integer('parent_message_id'),
    boolean('is_read', { default: false }),
  ]},
  { name: 'notifications', fields: [
    integer('school_id', { required: true, indexed: true }),
    integer('user_id', { indexed: true }),
    string('type', { default: 'info' }),
    string('title', { required: true }),
    text('body'),
    string('link'),
    string('channel', { default: 'in_app' }),
    boolean('is_read', { default: false, indexed: true }),
  ]},

  // Library
  { name: 'library_books', fields: [
    integer('school_id', { required: true }),
    string('title', { required: true }),
    string('author'),
    string('isbn'),
    string('publisher'),
    string('genre'),
    string('category'),
    string('cover_url'),
    text('description'),
    integer('total_copies', { default: 1 }),
    integer('available_copies', { default: 1 }),
    string('shelf_location'),
    string('barcode'),
    string('purchase_date'),
    integer('price'),
  ]},
  { name: 'library_loans', fields: [
    integer('school_id', { required: true }),
    integer('book_id', { required: true, indexed: true }),
    integer('borrower_id', { required: true, indexed: true }),
    integer('issued_by'),
    string('issue_date', { required: true }),
    string('due_date', { required: true }),
    string('return_date'),
    integer('renewals', { default: 0 }),
    integer('fine', { default: 0 }),
    boolean('fine_paid', { default: false }),
    string('status', { default: 'active', indexed: true }),
  ]},

  // Hostel
  { name: 'hostels', fields: [
    integer('school_id', { required: true }),
    string('name', { required: true }),
    string('type', { default: 'mixed' }),
    integer('warden_id'),
    integer('total_rooms', { default: 0 }),
    integer('total_beds', { default: 0 }),
  ]},
  { name: 'hostel_rooms', fields: [
    integer('hostel_id', { required: true }),
    string('room_number', { required: true }),
    integer('floor'),
    string('type', { default: 'double' }),
    integer('capacity', { default: 2 }),
    integer('occupants', { default: 0 }),
    string('status', { default: 'available' }),
  ]},
  { name: 'hostel_allocations', fields: [
    integer('school_id', { required: true }),
    integer('student_id', { required: true, indexed: true }),
    integer('room_id', { required: true, indexed: true }),
    string('academic_year', { required: true }),
    string('status', { default: 'active' }),
  ]},
  { name: 'hostel_checkins', fields: [
    integer('school_id', { required: true }),
    integer('student_id', { required: true }),
    integer('room_id'),
    string('type', { required: true }),
    string('timestamp', { required: true }),
    text('notes'),
    integer('recorded_by'),
  ]},
  { name: 'hostel_visitors', fields: [
    integer('school_id', { required: true }),
    string('visitor_name', { required: true }),
    string('visitor_phone'),
    string('visitor_relation'),
    integer('visiting_student_id'),
    integer('hostel_id'),
    string('time_in', { required: true }),
    string('time_out'),
    text('purpose'),
    text('notes'),
    integer('recorded_by'),
  ]},
  { name: 'hostel_maintenance_requests', fields: [
    integer('school_id', { required: true }),
    integer('hostel_id', { required: true }),
    integer('room_id'),
    string('title', { required: true }),
    text('description'),
    string('category', { default: 'other' }),
    string('priority', { default: 'medium' }),
    string('status', { default: 'pending' }),
    integer('reported_by'),
    string('assigned_to'),
    integer('cost'),
    text('notes'),
  ]},

  // Transport
  { name: 'vehicles', fields: [
    integer('school_id', { required: true }),
    string('name', { required: true }),
    string('plate_number'),
    string('type', { default: 'bus' }),
    integer('capacity'),
    integer('driver_id'),
    string('status', { default: 'active' }),
  ]},
  { name: 'transport_routes', fields: [
    integer('school_id', { required: true }),
    string('name', { required: true }),
    integer('vehicle_id'),
    json('stops', { required: true }),
    json('schedule'),
  ]},
  { name: 'transport_assignments', fields: [
    integer('school_id', { required: true }),
    integer('student_id', { required: true, indexed: true }),
    integer('route_id', { required: true, indexed: true }),
    string('stop_name'),
    string('status', { default: 'active' }),
  ]},
  { name: 'vehicle_maintenance', fields: [
    integer('school_id', { required: true }),
    integer('vehicle_id', { required: true }),
    string('service_type', { default: 'routine' }),
    text('description'),
    string('service_date', { required: true }),
    string('next_service_date'),
    integer('odometer'),
    integer('cost'),
    string('service_provider'),
    string('status', { default: 'scheduled' }),
    text('notes'),
  ]},
  { name: 'vehicle_documents', fields: [
    integer('school_id', { required: true }),
    integer('vehicle_id'),
    integer('driver_id'),
    string('document_type', { required: true }),
    string('document_number'),
    string('issue_date'),
    string('expiry_date', { required: true }),
    string('file_url'),
    text('notes'),
  ]},

  // Inventory
  { name: 'assets', fields: [
    integer('school_id', { required: true }),
    string('name', { required: true }),
    string('category'),
    string('serial_number'),
    text('description'),
    string('purchase_date'),
    integer('purchase_price'),
    integer('current_value'),
    integer('assigned_to'),
    string('location'),
    string('condition', { default: 'good' }),
  ]},
  { name: 'inventory_items', fields: [
    integer('school_id', { required: true }),
    string('name', { required: true }),
    string('category'),
    integer('quantity', { default: 0 }),
    integer('reorder_level', { default: 5 }),
    string('unit'),
    string('supplier'),
  ]},
  { name: 'suppliers', fields: [
    integer('school_id', { required: true }),
    string('name', { required: true }),
    string('contact_person'),
    string('email'),
    string('phone'),
    text('address'),
  ]},
  { name: 'purchase_requests', fields: [
    integer('school_id', { required: true }),
    integer('requested_by', { required: true }),
    integer('supplier_id'),
    json('items', { required: true }),
    integer('total_amount'),
    text('reason'),
    string('status', { default: 'pending' }),
    integer('approved_by'),
    string('approved_at'),
  ]},

  // Events
  { name: 'events', fields: [
    integer('school_id', { required: true }),
    string('title', { required: true }),
    text('description'),
    string('category', { required: true }),
    string('start_date', { required: true }),
    string('end_date'),
    string('start_time'),
    string('end_time'),
    string('venue'),
    boolean('is_recurring', { default: false }),
    string('recurrence_rule'),
    json('audience', { default: '[]' }),
    boolean('rsvp_required', { default: false }),
    string('image_url'),
  ]},
  { name: 'event_rsvps', fields: [
    integer('event_id', { required: true }),
    integer('user_id', { required: true }),
    string('response', { required: true }),
    integer('number_of_guests', { default: 0 }),
    text('notes'),
  ]},
  { name: 'venues', fields: [
    integer('school_id', { required: true }),
    string('name', { required: true }),
    string('type', { default: 'other' }),
    integer('capacity'),
    string('location'),
    json('facilities', { default: '[]' }),
    string('status', { default: 'available' }),
    text('notes'),
  ]},

  // Classroom
  { name: 'behavior_logs', fields: [
    integer('school_id', { required: true }),
    integer('student_id', { required: true }),
    string('type', { required: true }),
    string('category'),
    text('description'),
    integer('points', { default: 0 }),
    integer('recorded_by'),
  ]},
  { name: 'lesson_plans', fields: [
    integer('school_id', { required: true }),
    integer('teacher_id', { required: true }),
    integer('course_id'),
    string('title', { required: true }),
    string('week'),
    text('objectives'),
    text('materials'),
    text('activities'),
    text('assessment'),
    string('status', { default: 'draft' }),
  ]},
  { name: 'seating_plans', fields: [
    integer('school_id', { required: true }),
    integer('class_id', { required: true }),
    string('name', { required: true }),
    json('layout', { required: true }),
    integer('rows', { default: 5 }),
    integer('cols', { default: 6 }),
    boolean('is_default', { default: false }),
  ]},
  { name: 'interactive_lessons', fields: [
    integer('school_id', { required: true }),
    integer('teacher_id', { required: true }),
    integer('class_id'),
    integer('course_id'),
    string('title', { required: true }),
    text('description'),
    json('slides', { required: true }),
    string('mode', { default: 'live' }),
    string('status', { default: 'draft' }),
  ]},

  // IT Admin
  { name: 'audit_logs', fields: [
    integer('school_id', { required: true, indexed: true }),
    integer('user_id', { indexed: true }),
    string('action'),
    string('entity_type'),
    integer('entity_id'),
    text('details'),
    string('ip_address'),
  ]},
  { name: 'module_settings', fields: [
    integer('school_id', { required: true }),
    string('module_key', { required: true }),
    boolean('is_enabled', { default: true }),
    json('settings', { default: '{}' }),
  ]},
  { name: 'role_overrides', fields: [
    integer('school_id', { required: true }),
    integer('user_id', { required: true }),
    string('role', { required: true }),
    json('permissions', { default: '[]' }),
  ]},
  { name: 'fee_access_rules', fields: [
    integer('school_id', { required: true }),
    string('name', { required: true }),
    string('fee_type'),
    string('modules', { required: true }),
    string('action', { default: 'block' }),
    boolean('is_active', { default: true }),
  ]},

  // CBT
  { name: 'cbt_exams', fields: [
    integer('school_id', { required: true }),
    string('title', { required: true }),
    text('description'),
    text('instructions'),
    string('type', { required: true }),
    integer('duration'),
    integer('total_marks'),
    boolean('negative_marking', { default: false }),
    string('negative_mark_value'),
    string('access_mode', { default: 'restricted' }),
    string('scheduled_start'),
    string('scheduled_end'),
    integer('max_attempts', { default: 1 }),
    boolean('lockdown', { default: false }),
    boolean('proctoring', { default: false }),
    string('status', { default: 'draft' }),
    json('sections'),
  ]},
  { name: 'cbt_candidates', fields: [
    integer('exam_id', { required: true }),
    integer('user_id'),
    string('name', { required: true }),
    string('email'),
    string('access_pin'),
    string('status', { default: 'registered' }),
  ]},
  { name: 'cbt_attempts', fields: [
    integer('exam_id', { required: true, indexed: true }),
    integer('candidate_id', { required: true, indexed: true }),
    json('answers'),
    integer('score'),
    integer('total_marks'),
    integer('time_taken'),
    json('flags', { default: '[]' }),
    text('proctor_notes'),
    string('ip_address'),
    string('device_fingerprint'),
    json('integrity_report'),
    string('status', { default: 'in_progress' }),
  ]},
  { name: 'cbt_proctoring_logs', fields: [
    integer('attempt_id', { required: true }),
    string('event_type', { required: true }),
    string('timestamp', { required: true }),
    text('details'),
    string('severity', { default: 'warning' }),
  ]},

  // CMS / Website
  { name: 'about_pages', fields: [
    integer('school_id', { required: true }),
    text('content'),
    string('mission'),
    string('vision'),
    string('history'),
    string('image_url'),
  ]},
  { name: 'announcements', fields: [
    integer('school_id', { required: true }),
    string('title', { required: true }),
    string('slug', { required: true }),
    text('content', { required: true }),
    string('excerpt'),
    string('banner_image_url'),
    string('cta_text'),
    string('cta_url'),
    boolean('is_pinned', { default: false }),
    boolean('published', { default: true }),
  ]},
  { name: 'blog_posts', fields: [
    integer('school_id', { required: true }),
    string('title', { required: true }),
    string('slug', { required: true }),
    text('content', { required: true }),
    string('excerpt'),
    string('featured_image'),
    string('category'),
    string('tags'),
    string('author'),
    string('status', { default: 'draft' }),
  ]},
  { name: 'programs', fields: [
    integer('school_id', { required: true }),
    string('title', { required: true }),
    string('slug', { required: true }),
    text('content'),
    string('excerpt'),
    string('image_url'),
    string('category'),
    integer('sort_order', { default: 0 }),
    boolean('is_published', { default: true }),
  ]},
  { name: 'faqs', fields: [
    integer('school_id', { required: true }),
    string('question', { required: true }),
    text('answer', { required: true }),
    string('category'),
    integer('sort_order', { default: 0 }),
    boolean('is_published', { default: true }),
  ]},
  { name: 'gallery_items', fields: [
    integer('school_id', { required: true }),
    string('title'),
    string('url', { required: true }),
    string('type', { default: 'image' }),
    string('category'),
    string('album_id'),
    integer('sort_order', { default: 0 }),
  ]},
  { name: 'gallery_albums', fields: [
    integer('school_id', { required: true }),
    string('title', { required: true }),
    string('slug'),
    text('description'),
    string('cover_url'),
    string('type', { default: 'photo' }),
    boolean('is_published', { default: true }),
  ]},
  { name: 'banners', fields: [
    integer('school_id', { required: true }),
    string('title', { required: true }),
    text('content'),
    string('image_url'),
    string('link_url'),
    string('position', { default: 'top' }),
    string('cta_text'),
    string('start_date'),
    string('end_date'),
    boolean('is_active', { default: true }),
  ]},
  { name: 'popups', fields: [
    integer('school_id', { required: true }),
    string('title', { required: true }),
    text('content'),
    string('image_url'),
    string('position', { default: 'center' }),
    string('cta_text'),
    string('cta_url'),
    boolean('show_once', { default: false }),
    string('start_date'),
    string('end_date'),
    boolean('is_active', { default: true }),
  ]},
  { name: 'contact_info', fields: [
    integer('school_id', { required: true }),
    string('phone'),
    string('email'),
    text('address'),
    string('map_url'),
    string('latitude'),
    string('longitude'),
  ]},
  { name: 'contact_submissions', fields: [
    integer('school_id', { required: true }),
    string('name', { required: true }),
    string('email', { required: true }),
    string('phone'),
    text('message', { required: true }),
    string('form_type'),
    json('data'),
    string('status', { default: 'new' }),
  ]},
  { name: 'forms', fields: [
    integer('school_id', { required: true }),
    string('title', { required: true }),
    json('fields', { required: true }),
    string('success_message'),
    boolean('is_active', { default: true }),
  ]},
  { name: 'form_submissions', fields: [
    integer('form_id', { required: true }),
    integer('school_id', { required: true }),
    json('data', { required: true }),
    integer('submitted_by'),
    string('submitted_by_name'),
    string('submitted_by_email'),
    string('ip_address'),
    string('status', { default: 'new' }),
  ]},
  { name: 'admission_periods', fields: [
    integer('school_id', { required: true }),
    string('name', { required: true }),
    string('slug', { required: true }),
    string('academic_year', { required: true }),
    string('start_date'),
    string('end_date'),
    string('status', { default: 'upcoming' }),
    json('eligible_grades'),
    integer('available_seats'),
    integer('application_fee'),
    text('requirements_text'),
    json('process_steps'),
    json('important_dates'),
    string('contact_email'),
    string('contact_phone'),
  ]},
  { name: 'admission_applications', fields: [
    integer('school_id', { required: true }),
    integer('period_id', { required: true }),
    string('application_number', { required: true }),
    string('student_first_name', { required: true }),
    string('student_last_name', { required: true }),
    string('student_date_of_birth'),
    string('student_gender'),
    string('applying_for_grade'),
    string('parent_name', { required: true }),
    string('parent_email', { required: true }),
    string('parent_phone', { required: true }),
    text('previous_school'),
    text('special_needs'),
    text('notes'),
    string('status', { default: 'submitted' }),
    string('interview_date'),
    string('interview_time'),
    text('interview_notes'),
  ]},

  // Marketing
  { name: 'social_accounts', fields: [
    integer('school_id', { required: true }),
    string('platform', { required: true }),
    string('account_name'),
    string('access_token'),
    string('refresh_token'),
    boolean('is_connected', { default: false }),
    boolean('auto_post', { default: false }),
  ]},
  { name: 'social_posts', fields: [
    integer('school_id', { required: true }),
    json('platforms', { required: true }),
    text('content', { required: true }),
    string('image_url'),
    string('status', { default: 'draft' }),
    string('scheduled_at'),
    json('analytics'),
  ]},
  { name: 'email_lists', fields: [
    integer('school_id', { required: true }),
    string('name', { required: true }),
    text('description'),
  ]},
  { name: 'email_subscribers', fields: [
    integer('school_id', { required: true }),
    string('email', { required: true }),
    string('name'),
    integer('list_id'),
    string('status', { default: 'subscribed' }),
  ]},
  { name: 'email_campaigns', fields: [
    integer('school_id', { required: true }),
    string('subject', { required: true }),
    text('content', { required: true }),
    integer('list_id'),
    string('status', { default: 'draft' }),
    string('scheduled_at'),
    string('sent_at'),
  ]},
  { name: 'email_templates', fields: [
    integer('school_id', { required: true }),
    string('name', { required: true }),
    string('subject'),
    text('content'),
  ]},
  { name: 'email_automations', fields: [
    integer('school_id', { required: true }),
    string('name', { required: true }),
    string('trigger', { required: true }),
    text('description'),
    boolean('is_active', { default: false }),
  ]},

  // Platform
  { name: 'platform_blog_posts', fields: [
    string('title', { required: true }),
    string('slug', { required: true, unique: true }),
    text('content', { required: true }),
    string('excerpt'),
    string('featured_image'),
    string('category'),
    string('tags'),
    string('author'),
    string('status', { default: 'draft' }),
  ]},
  { name: 'platform_faqs', fields: [
    string('question', { required: true }),
    text('answer', { required: true }),
    string('category'),
    integer('sort_order', { default: 0 }),
    boolean('is_published', { default: true }),
  ]},
  { name: 'platform_settings', fields: [
    string('key', { required: true, unique: true }),
    text('value'),
  ]},
  { name: 'subscription_plans', fields: [
    string('name', { required: true }),
    string('slug', { required: true, unique: true }),
    text('description'),
    integer('price_monthly'),
    integer('price_yearly'),
    json('features', { default: '[]' }),
    integer('max_students'),
    integer('max_staff'),
    integer('max_storage_gb'),
    boolean('is_active', { default: true }),
    integer('sort_order', { default: 0 }),
  ]},
  { name: 'school_subscriptions', fields: [
    integer('school_id', { required: true }),
    integer('plan_id', { required: true }),
    string('status', { default: 'trial' }),
    string('current_period_start'),
    string('current_period_end'),
    string('trial_ends_at'),
    string('cancel_at'),
  ]},
  { name: 'support_tickets', fields: [
    integer('school_id'),
    integer('user_id', { required: true }),
    string('subject', { required: true }),
    text('description', { required: true }),
    string('status', { default: 'open' }),
    string('priority', { default: 'medium' }),
    integer('assigned_to'),
  ]},
  { name: 'support_ticket_replies', fields: [
    integer('ticket_id', { required: true }),
    integer('user_id', { required: true }),
    text('content', { required: true }),
  ]},
  { name: 'school_support_tickets', fields: [
    integer('school_id', { required: true }),
    integer('created_by', { required: true }),
    string('ticket_number', { required: true }),
    string('subject', { required: true }),
    text('description', { required: true }),
    string('status', { default: 'open' }),
    string('priority', { default: 'medium' }),
    integer('category_id'),
    integer('assigned_to'),
  ]},
  { name: 'school_ticket_categories', fields: [
    integer('school_id', { required: true }),
    string('name', { required: true }),
    text('description'),
    string('color'),
  ]},
  { name: 'class_subjects', fields: [
    integer('school_id', { required: true }),
    integer('class_id', { required: true }),
    string('subject_name', { required: true }),
    integer('teacher_id'),
    integer('course_id'),
    text('description'),
    integer('sort_order', { default: 0 }),
  ]},

  // AI
  { name: 'ai_settings', fields: [
    integer('school_id', { required: true }),
    string('key', { required: true }),
    text('value'),
  ]},
  { name: 'ai_conversations', fields: [
    integer('school_id', { required: true }),
    integer('user_id', { required: true }),
    string('title'),
    string('status', { default: 'active' }),
  ]},
  { name: 'ai_messages', fields: [
    integer('conversation_id', { required: true }),
    string('role', { required: true }),
    text('content', { required: true }),
    json('tool_calls'),
    json('tool_result'),
  ]},

  // Live Classes
  { name: 'live_class_rooms', fields: [
    integer('school_id', { required: true }),
    string('title', { required: true }),
    integer('course_id'),
    string('scheduled_start'),
    string('scheduled_end'),
    integer('created_by'),
    string('status', { default: 'scheduled', indexed: true }),
    string('meeting_url'),
    string('meeting_id'),
    string('passcode'),
    text('description'),
  ]},

  // Webhooks
  { name: 'webhooks', fields: [
    integer('school_id', { required: true }),
    string('name', { required: true }),
    string('url', { required: true }),
    json('events', { default: '[]' }),
    boolean('is_active', { default: true }),
    string('secret'),
  ]},
  { name: 'webhook_deliveries', fields: [
    integer('webhook_id', { required: true }),
    string('event', { required: true }),
    json('payload'),
    string('status', { default: 'pending' }),
    integer('attempts', { default: 0 }),
    string('response_code'),
    text('response_body'),
  ]},

  // Media
  { name: 'media_uploads', fields: [
    integer('school_id', { required: true }),
    integer('uploaded_by', { required: true }),
    string('file_name', { required: true }),
    string('original_name'),
    string('url', { required: true }),
    string('thumbnail_url'),
    string('type', { required: true }),
    string('mime_type'),
    integer('size'),
    integer('width'),
    integer('height'),
    string('cloudinary_id'),
    string('folder'),
    json('tags', { default: '[]' }),
  ]},
];

async function main() {
  console.log('=== Lightbase Collection Setup ===\n');
  console.log(`Base URL: ${client['config'].baseUrl}`);
  console.log(`Project: ${client['config'].project}`);
  console.log(`API Key: ${client['config'].apiKey.substring(0, 15)}...\n`);

  // Check connection
  const ping = await client.ping();
  if (!ping) {
    console.error('❌ Cannot connect to Lightbase. Check your credentials.');
    process.exit(1);
  }
  console.log('✅ Connected to Lightbase\n');

  let created = 0;
  let existing = 0;
  let failed = 0;

  for (const col of collections) {
    try {
      await client.ensureCollection(col.name, col.fields);
      // Check if it already existed
      const check = await client.getCollection(col.name);
      if (check) {
        existing++;
        console.log(`  ✓ ${col.name} (exists)`);
      } else {
        created++;
        console.log(`  ✨ ${col.name} (created)`);
      }
    } catch (e: any) {
      failed++;
      console.error(`  ❌ ${col.name}: ${e.message}`);
    }
  }

  console.log(`\n=== Summary ===`);
  console.log(`Created: ${created}`);
  console.log(`Existing: ${existing}`);
  console.log(`Failed: ${failed}`);
  console.log(`Total collections: ${collections.length}`);
}

main().catch(console.error);
